### ISSUE TITLE
NgForm not set to dirty for typeaheads

### ISSUE THREAD

**Issue by maurei** [maurei/ngx-table-editor#1]
eg for:

```ts
  public async onRowChange(event: RowChangeEvent<[MailFolder, NgForm]>) {

    if (event.previous.context && event.previous.context[1].dirty) {
      const folder = event.previous.context[0];
      const formControl = event.previous.context[1];
      folder.client.sync();
      if (formControl.form.controls.client.dirty) { // is never true
        console.log('client dirty!');
      }
      // await folder.update();
    }
  }
```
```html
      <table class="table" id=mail-folder tableEditor (rowChange)=onRowChange($event)>
        <thead>
          <tr>
            <th>Folder path</th>
            <th>Client</th>
            <th>Suggested</th>
            <th>Active</th>
          </tr>
        </thead>
        <tbody>
          <tr teRow ngForm #rowForm='ngForm' *ngFor='let folder of mailFolders;' [teContext]='[folder, rowForm]'  >
            <td name=path teCell [(ngModel)]=folder.path>
              <ng-container teAnchor></ng-container>
            </td>
            <td name=client teCell type=typeahead [typeahead]="clients" typeaheadOptionField="label" [(ngModel)]=folder.client.instance>
              <ng-container teAnchor></ng-container>
            </td>
            <td name=isSuggested teCell [(ngModel)]=folder.isSuggested>
              <ng-container teAnchor></ng-container>
            </td>
            <td>
              {{folder.inActive ? 'No' : 'Yes' }}
            </td>
          </tr>
        </tbody>
      </table>
```

**Comment by cloudy38** [comment]
> eg for:
> 
> ```ts
>   public async onRowChange(event: RowChangeEvent<[MailFolder, NgForm]>) {
> 
>     if (event.previous.context && event.previous.context[1].dirty) {
>       const folder = event.previous.context[0];
>       const formControl = event.previous.context[1];
>       folder.client.sync();
>       if (formControl.form.controls.client.dirty) { // is never true
>         console.log('client dirty!');
>       }
>       // await folder.update();
>     }
>   }
> ```
> 
> ```
>       <table class="table" id=mail-folder tableEditor (rowChange)=onRowChange($event)>
>         <thead>
>           <tr>
>             <th>Folder path</th>
>             <th>Client</th>
>             <th>Suggested</th>
>             <th>Active</th>
>           </tr>
>         </thead>
>         <tbody>
>           <tr teRow ngForm #rowForm='ngForm' *ngFor='let folder of mailFolders;' [teContext]='[folder, rowForm]'  >
>             <td name=path teCell [(ngModel)]=folder.path>
>               <ng-container teAnchor></ng-container>
>             </td>
>             <td name=client teCell type=typeahead [typeahead]="clients" typeaheadOptionField="label" [(ngModel)]=folder.client.instance>
>               <ng-container teAnchor></ng-container>
>             </td>
>             <td name=isSuggested teCell [(ngModel)]=folder.isSuggested>
>               <ng-container teAnchor></ng-container>
>             </td>
>             <td>
>               {{folder.inActive ? 'No' : 'Yes' }}
>             </td>
>           </tr>
>         </tbody>
>       </table>
> ```

Dick
